require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/identity_providers", type: :request do
  let(:valid_attributes) {
    {strategy: "google", name: "Google", availability: "shared", icon_url: "google-icon.jpg",
     client_id: "some-client-id", client_secret: "some-client-secret"}
  }

  let(:invalid_attributes) {
    {strategy: "", name: "", availability: "", icon_url: "",
     client_id: "", client_secret: ""}
  }

  # let(:user) { create(:user) }
  before { sign_in_as_admin }

  describe "GET /index" do
    it "renders a successful response" do
      get admin_identity_providers_url

      expect(response).to be_successful
      expect(response.body).to include(IdentityProvider.first.name) # From the admin user.
    end

    it "lists all identity providers" do
      identity_provider = IdentityProvider.create! valid_attributes
      get admin_identity_providers_url
      expect(response.body).to include(identity_provider.name)
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      identity_provider = IdentityProvider.create! valid_attributes
      get admin_identity_provider_url(identity_provider)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      # sign_in_as_admin

      get new_admin_identity_provider_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      identity_provider = IdentityProvider.create! valid_attributes
      get edit_admin_identity_provider_url(identity_provider)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new IdentityProvider" do
        expect {
          post admin_identity_providers_url, params: {identity_provider: valid_attributes}
        }.to change(IdentityProvider, :count).by(1)
      end

      it "redirects to the created admin_identity_provider" do
        post admin_identity_providers_url, params: {identity_provider: valid_attributes}
        expect(response).to redirect_to(admin_identity_provider_url(IdentityProvider.order(:created_at).last))

        follow_redirect!
        expect(response.body).to include("Identity provider was successfully created.")
      end
    end

    context "with invalid parameters" do
      it "does not create a new IdentityProvider" do
        expect {
          post admin_identity_providers_url, params: {identity_provider: invalid_attributes}
        }.to change(IdentityProvider, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admin_identity_providers_url, params: {identity_provider: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {strategy: "facebook", name: "Facebook", availability: "dedicated", icon_url: "fb-icon.jpg",
         client_id: "fb-client-id", client_secret: "fb-client-secret"}
      }

      it "updates the requested admin_identity_provider" do
        identity_provider = IdentityProvider.create! valid_attributes
        patch admin_identity_provider_url(identity_provider), params: {identity_provider: new_attributes}
        identity_provider.reload
        expect(identity_provider.strategy).to eq("facebook")
        expect(identity_provider.name).to eq("Facebook")
        expect(identity_provider.availability).to eq("dedicated")
        expect(identity_provider.icon_url).to eq("fb-icon.jpg")
        expect(identity_provider.client_id).to eq("fb-client-id")
        expect(identity_provider.client_secret).to eq("fb-client-secret")
      end

      it "redirects to the admin_identity_provider" do
        identity_provider = IdentityProvider.create! valid_attributes
        patch admin_identity_provider_url(identity_provider), params: {identity_provider: new_attributes}
        expect(response).to redirect_to(admin_identity_provider_url(identity_provider))

        follow_redirect!
        expect(response.body).to include("Identity provider was successfully updated.")
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        identity_provider = IdentityProvider.create! valid_attributes
        patch admin_identity_provider_url(identity_provider), params: {identity_provider: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_identity_provider" do
      identity_provider = IdentityProvider.create! valid_attributes
      expect {
        delete admin_identity_provider_url(identity_provider)
      }.to change(IdentityProvider, :count).by(-1)
    end

    it "redirects to the admin_identity_providers list" do
      identity_provider = IdentityProvider.create! valid_attributes
      delete admin_identity_provider_url(identity_provider)
      expect(response).to redirect_to(admin_identity_providers_url)

      follow_redirect!
      expect(response.body).to include("Identity provider was successfully destroyed.")
    end
  end
end
