require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/organizations", type: :request do
  let(:valid_attributes) {
    {name: "Test Org", subdomain: "test-org"}
  }

  let(:invalid_attributes) {
    {name: "", subdomain: "", credentials_attributes: {
      "1762823946994" => {
        identity_provider_attributes: {
          id: "", availability: "dedicated", strategy: "google_oauth2", name: "invalid-idp-name",
          icon_url: "    ", client_id: "    ", client_secret: ""
        },
        email_domains_attributes: {
          "1762823946995" => {domain_name: "___badbomain.com"}
        }
      }
    }}
  }

  # let(:user) { create(:user) }
  before { sign_in_as_admin }

  describe "GET /index" do
    it "renders a successful response" do
      create(:organization)
      get admin_organizations_url

      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      org = create(:organization)
      get admin_organization_url(org)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_organization_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      org = create(:organization)
      get edit_admin_organization_url(org)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Organization" do
        expect {
          post admin_organizations_url, params: {organization: valid_attributes}
        }.to change(Organization, :count).by(1)
      end

      it "redirects to the created organization" do
        post admin_organizations_url, params: {organization: valid_attributes}
        expect(response).to redirect_to(admin_organization_url(Organization.order(:created_at).last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Organization" do
        expect {
          post admin_organizations_url, params: {organization: invalid_attributes}
        }.to change(Organization, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admin_organizations_url, params: {organization: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.body).to include("invalid-idp-name")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:share_identity_provider) {
        IdentityProvider.find_by(strategy: "google_oauth2", availability: "shared") || create(:google_identity_provider)
      }
      let(:new_attributes) {
        {name: "new name", subdomain: "new-subdomain",
         shared_identity_provider_ids: [share_identity_provider.id],
         email_domains_attributes: [{domain_name: "example.com"}]}
      }

      it "updates the requested organization" do
        org = create(:organization)
        patch admin_organization_url(org), params: {organization: new_attributes}
        org.reload
        expect(org.name).to eq("new name")
        expect(org.subdomain).to eq("new-subdomain")
        expect(org.identity_providers.count).to eq(1)
        expect(org.identity_providers.first.strategy).to eq("google_oauth2")
        expect(org.email_domains.count).to eq(1)
        expect(org.email_domains.first.domain_name).to eq("example.com")
        expect(response).to redirect_to(admin_organization_url(org))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        org = create(:organization)
        patch admin_organization_url(org), params: {organization: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested org" do
      org = create(:organization)
      expect {
        delete admin_organization_url(org)
      }.to change(Organization, :count).by(-1)
      expect(response).to redirect_to(admin_organizations_url)
    end
  end
end
