require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/practices", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Practice. As you add validations to Practice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Practice.create! valid_attributes
      get admin_practices_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      practice = Practice.create! valid_attributes
      get admin_practice_url(practice)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      sign_in_as_admin

      get new_admin_practice_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      practice = Practice.create! valid_attributes
      get edit_admin_practice_url(practice)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Practice" do
        expect {
          post admin_practices_url, params: {practice: valid_attributes}
        }.to change(Practice, :count).by(1)
      end

      it "redirects to the created practice" do
        post admin_practices_url, params: {practice: valid_attributes}
        expect(response).to redirect_to(admin_practice_url(Practice.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Practice" do
        expect {
          post admin_practices_url, params: {practice: invalid_attributes}
        }.to change(Practice, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admin_practices_url, params: {practice: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested practice" do
        practice = Practice.create! valid_attributes
        patch admin_practice_url(practice), params: {practice: new_attributes}
        practice.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the practice" do
        practice = Practice.create! valid_attributes
        patch admin_practice_url(practice), params: {practice: new_attributes}
        practice.reload
        expect(response).to redirect_to(admin_practice_url(practice))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        practice = Practice.create! valid_attributes
        patch admin_practice_url(practice), params: {practice: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested practice" do
      practice = Practice.create! valid_attributes
      expect {
        delete admin_practice_url(practice)
      }.to change(Practice, :count).by(-1)
    end

    it "redirects to the practices list" do
      practice = Practice.create! valid_attributes
      delete admin_practice_url(practice)
      expect(response).to redirect_to(admin_practices_url)
    end
  end
end
